kind: Deployment 
apiVersion: apps/v1
metadata:
  name: lennardjohn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lennardjohn
  template:
    metadata:
      labels:
        app: lennardjohn
    spec:
      containers:
      - name: lennardjohn
        image: lennardjohn/docker-webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # resources:
        # limits:
        # cpu: 100m
        # memory: 512Mi
